apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airport-application
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: airportapp=kylo39/doom
    argocd-image-updater.argoproj.io/airportapp.force-update: "true"
    argocd-image-updater.argoproj.io/airportapp.helm.values: values.yaml
    argocd-image-updater.argoproj.io/airportapp.helm.image.tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git:repocreds
    argocd-image-updater.argoproj.io/git-branch: k8app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: airportapp
    server: https://kubernetes.default.svc
  project: default
  source:
    path: goz/airport-app
    repoURL: git@github.com/ru514n39/goz.git
    targetRevision: k8app
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true